### ISSUE TITLE
[버그] 가상하드디스크(VHD)가 연결된 경우 샌드박스 실행이 안됩니다

### ISSUE THREAD

**Issue by kblee0** [yourtablecloth/TableCloth#216]
**버그에 대한 설명**
가상하드디스크(VHD)가 연결된 경우 실행하기 버튼을 클릭해도 아무런 반응 없이 샌드박스 실행이 안됩니다

**재현 방법**
구체적으로 해당 증상을 재현하는 방법을 단계별로 최대한 상세하게 알려주세요.
1. 가상하드디스크를 디스크관리자에서 연결
2. 웹사이트 선택후 실행하기 클릭
3. 아무런 반응 없음
4. 디스크관리자에서 가상하드디스크를 분리
5. 웹사이트 선택후 실행하기 클릭
6. 정상 실행

**기대하는 동작**
가상하드디스크 연결 여부와 상관없이 실행 되게 해주세요.

**동영상 또는 스크린샷**
윈도우 이벤토로그내용:
Category: TableCloth.App
EventId: 0

Unexpected error occurred.

Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at TableCloth.Components.Implementations.Internals.Win32DiskDrive.GetPhysicalDisks(Nullable`1 timeout) in D:\a\TableCloth\TableCloth\src\TableCloth\Components\Implementations\Internals\Win32DiskDrive.cs:line 29
   at TableCloth.Components.Implementations.SystemProperties.IsSystemDiskAHardDrive() in D:\a\TableCloth\TableCloth\src\TableCloth\Components\Implementations\SystemProperties.cs:line 12
   at TableCloth.Components.Implementations.SandboxBuilder.GenerateSandboxConfigurationAsync(String outputDirectory, TableClothConfiguration tableClothConfiguration, IList`1 excludedDirectories, CancellationToken cancellationToken) in D:\a\TableCloth\TableCloth\src\TableCloth\Components\Implementations\SandboxBuilder.cs:line 72
   at TableCloth.Components.Implementations.SandboxLauncher.RunSandboxAsync(TableClothConfiguration config, CancellationToken cancellationToken) in D:\a\TableCloth\TableCloth\src\TableCloth\Components\Implementations\SandboxLauncher.cs:line 69
   at TableCloth.Commands.Shared.LaunchSandboxCommand.ExecuteAsync(ITableClothViewModel viewModel) in D:\a\TableCloth\TableCloth\src\TableCloth\Commands\Shared\LaunchSandboxCommand.cs:line 20
   at AsyncAwaitBestPractices.SafeFireAndForgetExtensions.HandleSafeFireAndForget[TException](Task task, Boolean continueOnCapturedContext, Action`1 onException)

**시스템 사양**
 - OS: Windows 11
 - CPU 아키텍처: x64
 - 브라우저: chrome
 - 소프트웨어 릴리스 버전: 1.13.2.0

**Comment by kblee0** [comment]
가상하드 디스크의 경우 SerialNumber 가 존재 하지 않습니다.
오류가 발생한 원인은 SerialNumber가 Null 인데 Trim을 하며 오류가 발생하는 것으로 보입니다.

**Comment by rkttu** [comment]
v1.14.0 출시와 함께 Sponge 프로그램을 제거하고, BitLocker나 하드디스크 타입 검사 관련 로직을 제거했습니다.
